[completion]
copilot = false
activate_on_typing = true

[display]
default_table_page_size = 10
default_width = "medium"
dataframes = "rich"
theme = "dark"
code_editor_font_size = 16
reference_highlighting = false
default_table_max_columns = 50
cell_output = "below"

[experimental]

[language_servers.basedpyright]

[language_servers.ty]

[language_servers.pylsp]
enable_pydocstyle = false
enable_ruff = true
enable_pylint = false
enable_pyflakes = false
enable_flake8 = false
enabled = false
enable_mypy = true

[save]
autosave = "after_delay"
format_on_save = false
autosave_delay = 1000

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[runtime]
auto_reload = "off"
on_cell_change = "autorun"
default_auto_download = []
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
default_sql_output = "auto"
reactive_tests = true
auto_instantiate = false
watcher_on_save = "lazy"

[package_management]
manager = "pip"

[mcp]
presets = []

[mcp.mcpServers]

[snippets]
custom_paths = []
include_default_snippets = true

[formatting]
line_length = 79

[ai]
inline_tooltip = false
rules = ""
mode = "manual"

[ai.models]
displayed_models = []
custom_models = []

[server]
browser = "default"
follow_symlink = false

[diagnostics]
sql_linter = true
